/**
 * Pure aggregation helpers used by the consolidation stubs. They produce
 * real, sensible output from the mapping step's per-code suggestion
 * blobs — no LLM in the loop. When the real prompts land, the runners
 * will hand these intermediate aggregates to the LLM instead of writing
 * them straight to the staging tables.
 *
 * Dedupe key is `articleTitle.trim().toLowerCase()` for new articles, and
 * `(articleId || articleTitle) + sectionId + sectionTitle` for section
 * updates. These are coarser than a real LLM merge would do but
 * preserve the round-trip shape so consumers downstream are exercised.
 */

import type { NewArticle, SectionUpdate } from '@/lib/pb/types';

export type MappedCodeWithSuggestions = {
  code: string;
  category: string | null;
  consolidationCategory: string | null;
  description: string | null;
  newArticlesNeeded: NewArticle[];
  existingArticleUpdates: SectionUpdate[];
};

export type AggregatedNewArticleRow = {
  articleTitle: string;
  category: string;
  numCodes: number;
  codes: string[];
  overallImportance?: number;
  justification: string;
};

export type AggregatedSectionUpdateRow = {
  articleTitle?: string;
  articleId?: string;
  sectionName?: string;
  sectionId?: string;
  exists?: boolean;
  newSection?: boolean;
  sectionUpdate?: boolean;
  category: string;
  numCodes: number;
  codes: string[];
  overallImportance?: number;
  justification: string;
};

function normTitle(t: string): string {
  return t.trim().toLowerCase();
}

function averageImportance(values: Array<number | undefined>): number | undefined {
  const nums = values.filter((v): v is number => typeof v === 'number');
  if (nums.length === 0) return undefined;
  const sum = nums.reduce((a, b) => a + b, 0);
  return Math.round((sum / nums.length) * 10) / 10;
}

/**
 * Dedupe `newArticlesNeeded` across the given codes by article title.
 * Each output row carries the union of contributing codes plus the average
 * importance score. `justification` is a stub marker so review-page rows
 * are visibly tagged as un-LLM'd until the real prompt swaps in.
 */
export function aggregateNewArticles(
  codes: MappedCodeWithSuggestions[],
  category: string,
): AggregatedNewArticleRow[] {
  const byTitle = new Map<
    string,
    {
      articleTitle: string;
      codes: Set<string>;
      importances: Array<number | undefined>;
    }
  >();
  for (const c of codes) {
    for (const a of c.newArticlesNeeded) {
      const title = a.articleTitle?.trim();
      if (!title) continue;
      const key = normTitle(title);
      const existing = byTitle.get(key);
      if (existing) {
        existing.codes.add(c.code);
        existing.importances.push(a.importance);
      } else {
        byTitle.set(key, {
          articleTitle: title,
          codes: new Set([c.code]),
          importances: [a.importance],
        });
      }
    }
  }
  return Array.from(byTitle.values()).map((row) => ({
    articleTitle: row.articleTitle,
    category,
    numCodes: row.codes.size,
    codes: Array.from(row.codes),
    overallImportance: averageImportance(row.importances),
    justification:
      'Generated by passthrough aggregation — real LLM consolidation not yet wired (see consolidation/prompts.ts).',
  }));
}

/**
 * Dedupe `existingArticleUpdates` by (articleId|articleTitle) + section
 * identifier. Each `SectionUpdate` from the mapping step covers an article
 * and an array of sections; we flatten so the staging row is one suggestion
 * = one section.
 */
export function aggregateSectionUpdates(
  codes: MappedCodeWithSuggestions[],
  category: string,
): AggregatedSectionUpdateRow[] {
  const byKey = new Map<
    string,
    {
      articleTitle?: string;
      articleId?: string;
      sectionName?: string;
      sectionId?: string;
      exists?: boolean;
      codes: Set<string>;
      importances: Array<number | undefined>;
    }
  >();
  for (const c of codes) {
    for (const upd of c.existingArticleUpdates) {
      const articleId = upd.articleId;
      const articleTitle = upd.articleTitle;
      const articleKey = articleId || articleTitle || '';
      const sections = upd.sections ?? [];
      if (sections.length === 0) {
        // Article-level update with no specific section; still surface it
        // so the editor sees the candidate. Key on articleId alone.
        const key = `${articleKey}::__article__`;
        const existing = byKey.get(key);
        if (existing) {
          existing.codes.add(c.code);
        } else {
          byKey.set(key, {
            articleTitle,
            articleId,
            sectionName: undefined,
            sectionId: undefined,
            exists: true,
            codes: new Set([c.code]),
            importances: [],
          });
        }
        continue;
      }
      for (const s of sections) {
        const sectionKey = s.sectionId || s.sectionTitle || '';
        const key = `${articleKey}::${sectionKey}`;
        const existing = byKey.get(key);
        if (existing) {
          existing.codes.add(c.code);
          existing.importances.push(s.importance);
        } else {
          byKey.set(key, {
            articleTitle,
            articleId,
            sectionName: s.sectionTitle,
            sectionId: s.sectionId,
            exists: s.exists,
            codes: new Set([c.code]),
            importances: [s.importance],
          });
        }
      }
    }
  }
  return Array.from(byKey.values()).map((row) => {
    const isNew = row.exists === false;
    return {
      articleTitle: row.articleTitle,
      articleId: row.articleId,
      sectionName: row.sectionName,
      sectionId: row.sectionId,
      exists: row.exists,
      newSection: isNew || undefined,
      sectionUpdate: row.exists === true || undefined,
      category,
      numCodes: row.codes.size,
      codes: Array.from(row.codes),
      overallImportance: averageImportance(row.importances),
      justification:
        'Generated by passthrough aggregation — real LLM consolidation not yet wired (see consolidation/prompts.ts).',
    };
  });
}
