import { Suspense } from 'react';
import { getCurrentUser } from '@/lib/auth';
import { listArticleBacklogForAssignee } from '@/lib/data/article-backlog';
import { computeSectionKey } from '@/lib/data/article-keys';
import { listArticleLitSearchRunsForArticleKeys } from '@/lib/data/article-lit-search-runs';
import { listArticleSourcesForArticleKeys } from '@/lib/data/article-sources';
import { listConsolidatedArticlesForKeys } from '@/lib/data/articles';
import { listCodes } from '@/lib/data/codes';
import { listReviewComments } from '@/lib/data/review-comments';
import { listConsolidatedSections } from '@/lib/data/sections';
import { listSpecialties } from '@/lib/data/specialties';
import { listAssignableUsers } from '@/lib/data/users';
import type {
  ArticleBacklogRecord,
  ArticleSourceRecord,
  ReviewCommentRecord,
} from '@/lib/pb/types';
import type { ConsolidatedSection } from '@/lib/types';
import {
  type CategoryLookup,
  type EmbeddedCode,
  extractCodes,
} from '../planning/_components/code-utils';
import type { SectionRow } from '../planning/_components/sections-view';
import { TableSkeleton } from '../planning/_components/table-skeleton';
import { type MyBacklogRow, MyBacklogView } from './_components/my-backlog-view';

export default function MyBacklogPage() {
  return (
    <Suspense fallback={<TableSkeleton columns={9} rows={10} />}>
      <MyBacklogData />
    </Suspense>
  );
}

function projectSection(slug: string, r: ConsolidatedSection): SectionRow {
  const codes = extractCodes(r.codes);
  const updateType: 'new' | 'update' | null =
    r.exists === true ? 'update' : r.exists === false ? 'new' : null;
  return {
    id: r.id,
    sectionKey:
      r.sectionKey ||
      computeSectionKey({
        specialtySlug: slug,
        articleTitle: r.articleTitle,
        articleId: r.articleId,
        sectionName: r.sectionName,
        sectionId: r.sectionId,
        category: r.category,
      }),
    articleTitle: r.articleTitle,
    articleId: r.articleId,
    sectionName: r.sectionName,
    sectionId: r.sectionId,
    updateType,
    category: r.category,
    codes,
    numCodes: r.numCodes ?? codes.length,
    overallImportance: r.overallImportance,
    overallCoverage: r.overallCoverage,
    justification: r.justification,
    previousSectionNames: r.previousSectionNames,
  };
}

function unionCodes(codes: EmbeddedCode[]): EmbeddedCode[] {
  const out: EmbeddedCode[] = [];
  const seen = new Set<string>();
  for (const c of codes) {
    if (seen.has(c.code)) continue;
    seen.add(c.code);
    out.push(c);
  }
  return out;
}

async function MyBacklogData() {
  const user = await getCurrentUser();
  if (!user?.email) {
    return <p>Sign in to see articles assigned to you.</p>;
  }

  const backlogRows = await listArticleBacklogForAssignee(user.email);
  const specialtySlugs = Array.from(new Set(backlogRows.map((r) => r.specialtySlug)));

  // type='new' rows resolve their current suggestion by `articleKey`
  // (stable across consolidation re-runs). Treat empty-string `type`
  // as 'new' too — PB's `select` field defaults to '' rather than
  // null when the column was added after a row was created, so the
  // `?? 'new'` fallback alone misses legacy rows.
  const newRowKeys = backlogRows
    .filter((r) => !r.type || r.type === 'new')
    .map((r) => r.articleKey)
    .filter((k): k is string => !!k);

  const [articleByKey, specialties, users, codesBySlug, commentsBySlug, sectionsBySlug] =
    await Promise.all([
      listConsolidatedArticlesForKeys(newRowKeys),
      listSpecialties(),
      listAssignableUsers(),
      Promise.all(
        specialtySlugs.map(async (slug) => [slug, await listCodes(slug)] as const),
      ),
      Promise.all(
        specialtySlugs.map(
          async (slug) => [slug, await listReviewComments(slug, 'article')] as const,
        ),
      ),
      Promise.all(
        specialtySlugs.map(
          async (slug) => [slug, await listConsolidatedSections(slug)] as const,
        ),
      ),
    ]);

  // Sources resolve by stable `articleKey` — the producer PB id can
  // be regenerated by a consolidation re-run, but the key survives,
  // so attached sources keep showing in the backlog drawer.
  const sourcesByKey = await listArticleSourcesForArticleKeys(newRowKeys);
  const litSearchRuns = await listArticleLitSearchRunsForArticleKeys(newRowKeys);

  // `listReviewComments` now returns comments grouped by `recordKey`
  // (the stable id). Merge across specialties into one flat map for
  // O(1) lookup in the view.
  const initialCommentsByArticle: Record<string, ReviewCommentRecord[]> = {};
  for (const [, byArticle] of commentsBySlug) {
    for (const [recordKey, list] of Object.entries(byArticle)) {
      initialCommentsByArticle[recordKey] = list;
    }
  }

  const specialtyNameBySlug: Record<string, string> = { _personal: '(No specialty)' };
  for (const s of specialties) specialtyNameBySlug[s.slug] = s.name;

  const categoryLookup: CategoryLookup = {};
  for (const [, codes] of codesBySlug) {
    for (const c of codes) categoryLookup[c.code] = c.category;
  }

  const sectionsBySpecialty = new Map(sectionsBySlug);

  const rows: MyBacklogRow[] = [];
  const initialBacklog: Record<string, ArticleBacklogRecord> = {};
  const initialSourcesByArticleKey: Record<string, ArticleSourceRecord[]> = {};

  for (const b of backlogRows) {
    const type = b.type || 'new';
    if (type === 'new') {
      // Resolve current consolidatedArticles row through the stable
      // articleKey. Zombies (key doesn't resolve) are silently skipped.
      const article = articleByKey[b.articleKey];
      if (!article?.id) continue;
      const currentId = article.id;
      rows.push({
        id: currentId,
        articleKey: b.articleKey,
        type: 'new',
        specialtySlug: b.specialtySlug,
        specialtyName: specialtyNameBySlug[b.specialtySlug] ?? b.specialtySlug,
        articleTitle: article.articleTitle,
        articleType: article.articleType,
        codes: extractCodes(article.codes),
        sourcesCount: sourcesByKey[b.articleKey]?.length ?? 0,
        registeredSourcesCount:
          sourcesByKey[b.articleKey]?.filter((s) => s.cortexSourceId).length ?? 0,
      });
      initialBacklog[b.articleKey] = b;
      initialSourcesByArticleKey[b.articleKey] = sourcesByKey[b.articleKey] ?? [];
    } else {
      // type='update': the backlog row's articleKey is `upd::<cms-articleId>`.
      // Resolve to *all* sections under the parent CMS articleId (not just
      // approved ones). The backlog row's existence — driven by the
      // editor's "Send to backlog" action — is the authoritative signal
      // that this article is queued for them; gating on approved sections
      // would silently hide assignments where the sections haven't been
      // re-approved yet (e.g. after a consolidation re-run cleared the
      // review map).
      const parentArticleId = b.articleRecordId;
      const sectionRecs = sectionsBySpecialty.get(b.specialtySlug) ?? [];
      const allSections = sectionRecs
        .filter((s) => s.articleId === parentArticleId && s.sectionKey)
        .map((s) => projectSection(b.specialtySlug, s));
      rows.push({
        id: parentArticleId,
        articleKey: b.articleKey,
        type: 'update',
        specialtySlug: b.specialtySlug,
        specialtyName: specialtyNameBySlug[b.specialtySlug] ?? b.specialtySlug,
        articleTitle: allSections[0]?.articleTitle ?? '(untitled update)',
        articleType: undefined,
        codes: unionCodes(allSections.flatMap((s) => s.codes)),
        sourcesCount: 0,
        registeredSourcesCount: 0,
        sections: allSections,
      });
      initialBacklog[b.articleKey] = b;
    }
  }

  rows.sort(
    (a, b) =>
      (a.specialtyName ?? '').localeCompare(b.specialtyName ?? '') ||
      (a.articleTitle ?? '').localeCompare(b.articleTitle ?? ''),
  );

  return (
    <MyBacklogView
      rows={rows}
      categoryLookup={categoryLookup}
      assignableUsers={users}
      specialties={specialties.map((s) => ({ slug: s.slug, name: s.name }))}
      initialBacklog={initialBacklog}
      initialSourcesByArticleKey={initialSourcesByArticleKey}
      initialLitSearchRuns={litSearchRuns}
      initialCommentsByArticle={initialCommentsByArticle}
      viewerEmail={user.email}
      viewerRole={user.role}
    />
  );
}
